@startuml
'https://plantuml.com/sequence-diagram

autonumber

header System sekvens diagram
actor Bruger

title CatHomeGUI
  Bruger <-- System: LoginScreen

    alt Existing User
        Bruger -> System: Type Email and Password
        Bruger -> System: Login pressed
        Bruger <-- System: Shows HomeSite
    else New User
        Bruger -> System: Register
        Bruger -> System: Type details
        Bruger <-- System: Account created
        Bruger <-- System: LoginScreen

    end
    note left of Bruger: HomeSite
    alt MyAccount
    Bruger -> System: MyAccount Pressed
    Bruger <-- System: Shows AccountDetailsSite
    Bruger <-- System: Shows name,email,password
    alt EditAccountDetails
    Bruger -> System: EditAccountDetails
    Bruger <-- System: Shows EditAccountSite
    Bruger -> System: User changes Details
    Bruger -> System: User presses Confirm
    Bruger <-- System: Changes details

end
alt Pets
    Bruger -> System: EditAccountDetails pressed
    Bruger <-- System: Shows EditAccountSite
    Bruger -> System: User changes Details
    Bruger -> System: User presses Confirm
    Bruger <-- System: Changes details

    alt Editpets
        Bruger -> System: Editpets pressed
        Bruger <-- System: Shows EditPetSite
        Bruger -> System: User changes Details
        Bruger -> System: User presses Confirm
        Bruger <-- System: Changes details
        end

    end
end
note left of Bruger: HomeSite
 alt Gallery
    Bruger -> System: Gallery pressed
    Bruger <-- System: Shows Gallery
end

note left of Bruger: HomeSite
 alt Events
    Bruger -> System: Events Pressed
    Bruger <-- System: Shows Events

end
@enduml